
services:

  # Building and testing environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/btc-raspberrypiclub/jeopardy:latest
    stdin_open: true
    tty: true
    volumes:
      #- ${PWD}:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY:-:0}
    devices:
      - /dev/snd:/dev/snd
    privileged: true
    profiles:
      - develop
    command: ["/usr/local/bin/python","-vvvv", "start.py"]

  app:
    image: ghcr.io/btc-raspberrypiclub/jeopardy:latest
    stdin_open: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - PW_AUDIO_MODULE=pipewire
    privileged: true

