
services:

  # Developing and testing environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/btc-raspberrypiclub/jeopardy:latest
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    # Bring the DISPLAY through from the host
    environment:
      - DISPLAY=${DISPLAY:-:0}
    devices:
      - /dev/snd:/dev/snd
    privileged: true
    # This service can only be interacted with by specifying 
    # '--profile develop' on the commandline, otherwise it is ignored
    profiles:
      - develop
    # Running python in verbose mode helps debugging
    command: ["/usr/local/bin/python","-vvvv", "start.py"]


  # The actual application service for live 
  app:
    image: ghcr.io/btc-raspberrypiclub/jeopardy:latest
    stdin_open: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - PW_AUDIO_MODULE=pipewire
    privileged: true

